[project]
name = "several-tasks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
]


[tool.pytest.ini_options]
python_files = "test_*.py"
addopts = "--no-header -s"
